config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :users, :only => [:show]
  resources :events do
    member do
      get 'like'
    end
  end
  get 'events/index'

  root :to => 'events#index'

  get '/signout' => 'sessions#destroy', :as => :signout

  get '/signin' => 'sessions#new', :as => :signin

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :user
  geocoded_by :address
  after_validation :geocode
  make_flaggable

  has_many :flaggings, :class_name => "MakeFlaggable::Flagging", :as => :flaggable

  include PublicActivity::Model
  tracked

end

app/models/flaggings.rb
class MakeFlaggable::Flagging < ActiveRecord::Base
  belongs_to :flaggable, :polymorphic => true
  belongs_to :flagger, :polymorphic => true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:facebook]

         has_many :events
         make_flagger :flag_once => true
         has_many :flaggings, :class_name => "MakeFlaggable::Flagging", :as => :flagger
         has_many :flagged_items, :through => :flaggings, :source => :flaggable, :source_type => 'Event'

         def self.from_omniauth(auth)
           where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
             user.email = auth.info.email
             user.password = Devise.friendly_token[0,20]
             user.name = auth.info.name   # assuming the user model has a name
             user.image = auth.info.image # assuming the user model has an image
           end
         end

         def facebook
           # You need to implement the method below in your model (e.g. app/models/user.rb)
           @user = User.from_omniauth(request.env["omniauth.auth"])

           if @user.persisted?
             sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
             set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
           else
             session["devise.facebook_data"] = request.env["omniauth.auth"]
             redirect_to new_user_registration_url
           end
         end

         def failure
           redirect_to root_path
         end

         def self.new_with_session(params, session)
  super.tap do |user|
    if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
      user.email = data["email"] if user.email.blank?
    end
  end
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:email, :password, :password_confirmation, :name) }
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :load_activities, only: [:index, :show, :new, :edit]



  def like
    @event = Event.find(params[:id])

    if current_user.flagged?(@event, :like)
      current_user.unflag(@event, :like)
      msg = "Je gaat niet meer naar dit evenement"

    else
      @event.create_activity :like
      current_user.flag(@event, :like)
      msg = "Je gaat naar dit evenement"
    end
    redirect_to events_path, :notice => msg
  end



  # GET /events
  # GET /events.json

  def index
    @userLocation = cookies[:lat_lng]
    @events = Event.all
    @nearbylocations = Event.near(@userLocation, 5)
  end

  # GET /events/1
  # GET /events/1.json
  def show

  end

  # GET /events/new
  def new
    @event = current_user.events.build
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = current_user.events.build(event_params)


    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end

  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find_by(id: params[:id])
    end

    def load_activities
      @activities = PublicActivity::Activity.order('created_at DESC')
    end

    def correct_user
      @pin = current_user.events.find_by(id: params[:id])
      redirect_to events_path, notice: "Not authorized to edit this event" if @pin.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:event_id, :description, :address, :date, :generated, :latitude, :longitude)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/notifications_controller.rb
def index
  @activities = PublicActivity::Activity.all
end

app/controllers/pusher_controller.rb
class PusherController < ApplicationController
  protect_from_forgery :except => :auth # stop rails CSRF protection for this action

  def auth
    if current_user
      response = Pusher[params[:channel_name]].authenticate(params[:socket_id])
      render :json => response
    else
      render :text => "Not authorized", :status => '403'
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def facebook
      # You need to implement the method below in your model (e.g. app/models/user.rb)
      @user = User.from_omniauth(request.env["omniauth.auth"])

      if @user.persisted?
        sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
        set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
      else
        session["devise.facebook_data"] = request.env["omniauth.auth"]
        redirect_to new_user_registration_url
      end
    end

    def failure
      redirect_to root_path
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
  def toggle_like_button(event, user)
    if current_user.flagged?(event, :like)
      link_to "Ik ga niet meer", like_event_path(event)
    else
      link_to "Ik ga hier heen", like_event_path(event)
  end
end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :event_id %><br>
    <%= f.text_field :event_id %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.datetime_select :date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<%= render "shared/menu" %>
<h1>Editing Event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?sensor=false"></script>


<div class="jumbotron">
  <div class="container">
    <h1>Hello, world!</h1>
    <p>This is a template for a simple marketing or informational website. It includes a large callout called a jumbotron and three supporting pieces of content. Use it as a starting point to create something more unique.</p>
    <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more &raquo;</a></p>
  </div>
</div>

<%- unless @lat_lng %>
<script>
  getGeoLocation();
</script>
<%- end %>

<%= render "shared/menu" %>

<div class="row">
  <div class="container">

  <div class="col-lg-12">

    <% if user_signed_in? %>
      <%= link_to 'Nieuw evenement aanmaken', new_event_path, :class => "btn btn-primary" %>
    <% end %>

<h2>Bij jou in de buurt (<%= @userLocation %>)</h2>
    <% @nearbylocations.each do |event| %>
      <%= link_to event.event_id, event %>
    <% end %>

    <h2>Alle evenementen</h2>

    <% @events.each do |event| %>
        <div class="panel">
          <div class="panel-heading"><h3 class="panel-title"><%= link_to event.event_id, event %></h3></div>
            <div class="panel-body">
            <span class="eventDescription"><%= event.description %></span>
            <span class="eventAddress">Adres: <%= event.address %></a>
            <span class="eventDate">Datum: <%= event.date %></span>
            <span class="eventCreatedAt">Aangemaakt op: <%= event.created_at %></span>
            <span class="eventCreator">Aangemaakt door: <%= link_to event.user.name, event.user %></span>
            <span class="eventAttendees">Aantal deelnemers: <span class="badge"><%= event.flaggings.length %></span></span>
            <span class="eventEdit">
            </div>
            <div class="panel-footer">
            <% if event.user == current_user %>
              <%= link_to 'Bewerken', edit_event_path(event) %>
              <%= link_to 'Verwijderen', event, method: :delete, data: { confirm: 'Are you sure?' } %>
            <% end %>

            <% if user_signed_in? %>
              <%= toggle_like_button(event, @current_user) %>
            <% end %>
          </span>
          </div>

        </div>
      <% end %>


      <h3>Activities</h3>
      <div><%= render 'shared/activities' %></div>


<br />



<div id="map" style="width: 600px; height: 500px; clear:both;"></div>


<script type="text/javascript">
  // Create the map
  var map = new google.maps.Map(document.getElementById("map"), {
    mapTypeId: google.maps.MapTypeId.ROADMAP
  });

  // Initialize the bounds container
  var bounds = new google.maps.LatLngBounds();

  <% @events.each do |event| %>
    // Create the LatLng
    var latLng = new google.maps.LatLng(<%= event.latitude %>, <%= event.longitude %>);

    // Create the marker
    var marker = new google.maps.Marker({
        position: latLng,
        map: map,
        title: '<%= escape_javascript(event.event_id) %>'
    });



    google.maps.event.addListener(marker, 'click', function() {
      document.location = '<%= event_path(event) %>';
    });

    // Extend the bounds
    bounds.extend(latLng);
  <% end %>

  // Fit to bounds
  map.fitBounds(bounds);
</script>
</div>
</div>

app/views/events/new.html.erb
<%= render "shared/menu" %>
<div class="row">
  <div class="container">
    <div class="col-lg-12">

      <h1>New Event</h1>

      <%= render 'form' %>

      <%= link_to 'Back', events_path %>
    </div>
  </div>
</div>

app/views/events/show.html.erb
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?sensor=false"></script>

<%= render "shared/menu" %>

<p class="alert" role="alert"><%= notice %></p>

<div class="row">
  <div class="container">
  <div class="col-lg-12">

<h1>Kaartje</h2>

  <div id="map" style="width: 600px; height: 500px;"></div>

  <script>
  // Create the map
  var map = new google.maps.Map(document.getElementById("map"), {
    mapTypeId: google.maps.MapTypeId.ROADMAP
  });

  // Initialize the bounds container
  var bounds = new google.maps.LatLngBounds();

    // Create the LatLng
    var latLng = new google.maps.LatLng(<%= @event.latitude %>, <%= @event.longitude %>);

    // Create the marker
    var marker = new google.maps.Marker({
        position: latLng,
        map: map,
    });

    // Extend the bounds
    bounds.extend(latLng);

  // Fit to bounds
  map.fitBounds(bounds);
  </script>





<h2>Evenementdetails</h2>
<p>
  <strong>Titel:</strong>
  <%= @event.event_id %>
</p>

<p>
  <strong>Omschrijving:</strong>
  <%= @event.description %>
</p>

<p>
  <strong>Adres:</strong>
  <%= @event.address %>
</p>


<p>
  <strong>Datum:</strong>
  <%= @event.date %>
</p>

<p>
  <strong>Aangemaakt op:</strong>
  <%= @event.created_at %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @event.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @event.longitude %>
</p>


<br><br>
<% if @event.user == current_user %>
  <%= link_to 'Bewerken', edit_event_path(@event) %>
<% end %>
<%= link_to 'Terug naar overzicht', events_path %>

</div>
</div>
</div>

app/views/home/index.html.erb
<ul>
<% flash.each do |key, msg| %>
  <%= content_tag :li, msg, id: key %>
<% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Yuppia</title>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag "defaults", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag 'defaults', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% flash.each do |name, msg| %>
       <%= content_tag(:div, msg, class: "alert alert-#{name}") %>
  <% end %>
<%= yield %>

</body>
</html>

app/views/public_activity/event/_attend.html.erb
<li class="list-group-item">
  <%= a.trackable.event_id %> is being attended.
</li>

app/views/public_activity/event/_create.html.erb
<li class="list-group-item">
  <%= link_to a.trackable.event_id, a.trackable %> is aangemaakt door <%= link_to a.trackable.user.name, a.trackable.user %>.


</li>

app/views/public_activity/event/_destroyed.html.erb
<li class="list-group-item">
  <%= a.trackable.title %> was deleted.
</li>

app/views/public_activity/event/_like.html.erb
<li class="list-group-item">
  <%= link_to a.trackable.user.name, a.trackable.user %> gaat naar <%= link_to a.trackable.event_id, a.trackable %>.
</li>

app/views/public_activity/event/_update.html.erb
<li class="list-group-item">
  <%= a.trackable.title %> was edited.
</li>

app/views/shared/_activities.html.erb
<div class="col-sm-3">
  <ul class="list-group">
    <%= render_activities @activities %>
  </ul>
</div>

app/views/shared/_menu.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
  <%= link_to "Yuppia", root_path, :class => "navbar-brand" %>
  <ul class="nav navbar-nav">
    <li class="nav-item active">
      <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
    </li>
  </ul>
  <ul class="nav navbar-nav navbar-right">
    <% if user_signed_in? %>
          <li><%= link_to current_user.name, edit_user_registration_path, :class => "nav-link" %></li>
          <li><%= link_to "Log out", destroy_user_session_path, method: :delete, :class => "nav-link" %></li>
         <% else %>
          <li><%= link_to "Log in", new_user_session_path, class: "btn btn-default btn-lg" %></li>
          <li><%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg" %></li>
      <% end %>
  </ul>
</div>
</nav>

app/views/users/show.html.erb
<%= render "shared/menu" %>
<div class="row">
  <div class="container">
    <div class="col-lg-12">
      <h1>Profielpagina voor gebruiker</h1>
      <%= @user.email %>

      <h2>Hier gaat deze gebruiker heen</h2>
      <ul>
      <% @user.flagged_items.each do |event| %>
        <li><%= link_to event.event_id %> op <%= event.date %></li>
      <% end %>
      </ul>
    </div>
  </div>
</div>